/**
 * 行为层拟人增强模块 — 对抗 Boss 直聘行为分析
 *
 * 社区确认的检测维度：
 * 1. performance.now 时序探针
 * 2. 鼠标轨迹贝塞尔曲线
 * 3. IME 输入法事件流（compositionstart/update/end）
 * 4. zhipin-sign WASM 行为神经网络
 * 5. 输入法标志位上报
 */

import type { CDPSession, Page } from 'puppeteer-core';
import { randomIntInclusive, sleep } from '../browser/timing.js';

// ─────────────────────────────────────────────────────────────────────────────
// §1 performance.now Hook
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Hook performance.now 为单调递增值。
 * 关键：不能返回固定值（t1===t2 会被判定为 hook 并触发内存炸弹），
 * 必须随时间自然递增，只是消除 CDP 序列化带来的异常跳跃。
 */
export const PERFORMANCE_NOW_HOOK_SCRIPT = `(function() {
  'use strict';
  var _perfProto = Performance.prototype;
  var _origNow = _perfProto.now;
  var _timeOrigin = performance.timeOrigin || Date.now();
  var _lastValue = 0;

  // 使用 Date.now() - timeOrigin 作为基准时间，模拟真实行为
  // 加入微小随机抖动（0-0.1ms）模拟真实时钟精度
  var hookedNow = function now() {
    var real = Date.now() - _timeOrigin;
    // 保证严格单调递增
    if (real <= _lastValue) {
      real = _lastValue + Math.random() * 0.1 + 0.001;
    }
    _lastValue = real;
    return real;
  };

  // 伪装为 native 函数
  var _origToString = Function.prototype.toString;
  var _nativeMap = new Map();
  _nativeMap.set(hookedNow, 'function now() { [native code] }');
  var _fakeToString = function toString() {
    var mapped = _nativeMap.get(this);
    return mapped || _origToString.call(this);
  };
  _nativeMap.set(_fakeToString, 'function toString() { [native code] }');

  try {
    Object.defineProperty(Function.prototype, 'toString', {
      value: _fakeToString, writable: true, configurable: true
    });
  } catch(e) {}

  try {
    Object.defineProperty(_perfProto, 'now', {
      value: hookedNow,
      writable: true,
      configurable: true,
      enumerable: false,
    });
  } catch(e) {}
})();`;

// ─────────────────────────────────────────────────────────────────────────────
// §2 贝塞尔曲线鼠标轨迹
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 生成三次贝塞尔曲线上的点序列，模拟真人鼠标轨迹。
 * 包含速度变化（加速-匀速-减速）和微小随机抖动。
 */
function bezierCurvePoints(
  startX: number, startY: number,
  endX: number, endY: number,
  steps: number,
): Array<{ x: number; y: number }> {
  // 控制点：在起点和终点之间随机偏移，模拟人手弧线
  const cp1x = startX + (endX - startX) * (0.2 + Math.random() * 0.3);
  const cp1y = startY + (endY - startY) * (Math.random() * 0.8 - 0.4);
  const cp2x = startX + (endX - startX) * (0.5 + Math.random() * 0.3);
  const cp2y = endY + (endY - startY) * (Math.random() * 0.4 - 0.2);

  const points: Array<{ x: number; y: number }> = [];
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    // 缓动函数：ease-in-out（开始和结束慢，中间快）
    const easedT = t < 0.5
      ? 2 * t * t
      : 1 - Math.pow(-2 * t + 2, 2) / 2;

    const x = Math.pow(1 - easedT, 3) * startX
      + 3 * Math.pow(1 - easedT, 2) * easedT * cp1x
      + 3 * (1 - easedT) * Math.pow(easedT, 2) * cp2x
      + Math.pow(easedT, 3) * endX;
    const y = Math.pow(1 - easedT, 3) * startY
      + 3 * Math.pow(1 - easedT, 2) * easedT * cp1y
      + 3 * (1 - easedT) * Math.pow(easedT, 2) * cp2y
      + Math.pow(easedT, 3) * endY;

    // 微小随机抖动 (±1px)，终点不抖
    const jitterX = i === steps ? 0 : (Math.random() - 0.5) * 2;
    const jitterY = i === steps ? 0 : (Math.random() - 0.5) * 2;

    points.push({
      x: Math.round((x + jitterX) * 100) / 100,
      y: Math.round((y + jitterY) * 100) / 100,
    });
  }
  return points;
}

/**
 * 用贝塞尔曲线移动鼠标到目标位置，模拟真人轨迹。
 */
export async function humanMouseMove(
  page: Page,
  targetX: number,
  targetY: number,
  options?: { startX?: number; startY?: number; steps?: number },
): Promise<void> {
  const startX = options?.startX ?? (Math.random() * 200 + 100);
  const startY = options?.startY ?? (Math.random() * 200 + 100);
  const steps = options?.steps ?? randomIntInclusive(15, 35);

  const points = bezierCurvePoints(startX, startY, targetX, targetY, steps);

  for (const point of points) {
    await page.mouse.move(point.x, point.y);
    // 每步之间 5-20ms 随机延迟
    await sleep(randomIntInclusive(5, 20));
  }
}

/**
 * 贝塞尔曲线移动 + 点击，模拟真人点击。
 */
export async function humanClick(
  page: Page,
  x: number,
  y: number,
  options?: { startX?: number; startY?: number },
): Promise<void> {
  await humanMouseMove(page, x, y, options);
  // 点击前短暂停顿（人的反应时间）
  await sleep(randomIntInclusive(50, 150));
  // 按下-抬起随机间隔
  await page.mouse.down();
  await sleep(randomIntInclusive(55, 180));
  await page.mouse.up();
}

/**
 * 对 selector 元素执行拟人点击（先获取元素中心坐标，再贝塞尔曲线移动+点击）。
 */
export async function humanClickSelector(
  page: Page,
  selector: string,
): Promise<void> {
  const box = await page.evaluate((sel: string) => {
    const el = document.querySelector(sel);
    if (!el) return null;
    const rect = el.getBoundingClientRect();
    return {
      x: rect.x + rect.width / 2,
      y: rect.y + rect.height / 2,
    };
  }, selector);

  if (!box) throw new Error(`元素未找到: ${selector}`);

  await humanClick(page, box.x, box.y);
}

// ─────────────────────────────────────────────────────────────────────────────
// §3 IME 中文输入法事件流模拟
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 通过 CDP Input.dispatchKeyEvent 发送完整的 IME 输入事件流。
 * 模拟真实中文输入法行为：
 * compositionstart → compositionupdate (逐字) → compositionend → input
 *
 * Boss 检测维度：
 * - "未通过输入法输入中文" 标志位
 * - IME 事件流完整性
 * - 击键时序模式
 */
export async function typeChineseWithIME(
  page: Page,
  text: string,
  selector?: string,
): Promise<void> {
  // 先聚焦目标元素
  if (selector) {
    await page.click(selector);
    await sleep(randomIntInclusive(100, 300));
  }

  const cdp = await page.createCDPSession();

  try {
    // 将文本按"词"拆分（每 2-4 字一组，模拟输入法上屏）
    const chunks = splitIntoIMEChunks(text);

    for (const chunk of chunks) {
      // 1. compositionstart
      await cdp.send('Input.dispatchKeyEvent', {
        type: 'rawKeyDown',
        key: 'Process',
        code: '',
        windowsVirtualKeyCode: 229, // VK_PROCESSKEY - IME 标志
        nativeVirtualKeyCode: 229,
      });

      await page.evaluate((sel: string | undefined) => {
        const el = sel ? document.querySelector(sel) : document.activeElement;
        if (!el) return;
        el.dispatchEvent(new CompositionEvent('compositionstart', {
          bubbles: true, cancelable: true, data: '',
        }));
      }, selector);

      await sleep(randomIntInclusive(30, 80));

      // 2. compositionupdate — 逐字符模拟拼音候选过程
      let composingText = '';
      for (let i = 0; i < chunk.length; i++) {
        composingText += chunk[i];

        await page.evaluate((sel: string | undefined, data: string) => {
          const el = sel ? document.querySelector(sel) : document.activeElement;
          if (!el) return;
          el.dispatchEvent(new CompositionEvent('compositionupdate', {
            bubbles: true, cancelable: true, data,
          }));
          // 同时触发 input 事件（isComposing: true）
          el.dispatchEvent(new InputEvent('input', {
            bubbles: true, cancelable: false, inputType: 'insertCompositionText',
            data, isComposing: true,
          }));
        }, selector, composingText);

        // 模拟击键间隔（拼音输入节奏）
        await sleep(randomIntInclusive(60, 180));
      }

      // 3. compositionend — 选词上屏
      await page.evaluate((sel: string | undefined, data: string) => {
        const el = sel ? document.querySelector(sel) : document.activeElement;
        if (!el) return;
        el.dispatchEvent(new CompositionEvent('compositionend', {
          bubbles: true, cancelable: true, data,
        }));
        // 最终 input 事件（isComposing: false）
        el.dispatchEvent(new InputEvent('input', {
          bubbles: true, cancelable: false, inputType: 'insertFromComposition',
          data, isComposing: false,
        }));
      }, selector, chunk);

      // keyup Process
      await cdp.send('Input.dispatchKeyEvent', {
        type: 'keyUp',
        key: 'Process',
        code: '',
        windowsVirtualKeyCode: 229,
        nativeVirtualKeyCode: 229,
      });

      // 词与词之间的停顿（思考下一个词的时间）
      await sleep(randomIntInclusive(200, 600));
    }

    // 最后手动设置输入框的值（确保 React/Vue 状态同步）
    if (selector) {
      await page.evaluate((sel: string, val: string) => {
        const el = document.querySelector(sel) as HTMLInputElement | HTMLTextAreaElement | null;
        if (!el) return;
        // 获取 React fiber 内部的 value tracker
        const nativeInputValueSetter = Object.getOwnPropertyDescriptor(
          window.HTMLInputElement.prototype, 'value'
        )?.set || Object.getOwnPropertyDescriptor(
          window.HTMLTextAreaElement.prototype, 'value'
        )?.set;
        if (nativeInputValueSetter) {
          nativeInputValueSetter.call(el, val);
        } else {
          el.value = val;
        }
        el.dispatchEvent(new Event('change', { bubbles: true }));
      }, selector, text);
    }
  } finally {
    await cdp.detach().catch(() => {});
  }
}

/**
 * 将文本拆分为 IME 上屏块（2-4 字一组），模拟真实输入法选词行为。
 */
function splitIntoIMEChunks(text: string): string[] {
  const chars = Array.from(text);
  const chunks: string[] = [];
  let i = 0;
  while (i < chars.length) {
    const chunkSize = Math.min(
      randomIntInclusive(2, 4),
      chars.length - i,
    );
    chunks.push(chars.slice(i, i + chunkSize).join(''));
    i += chunkSize;
  }
  return chunks;
}

// ─────────────────────────────────────────────────────────────────────────────
// §4 zhipin-sign WASM 拦截
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 需要在 boss_page_guards.ts 的 Fetch.enable patterns 中追加的规则。
 * zhipin-sign iframe 内嵌的 WASM 行为分析模块。
 */
export const ZHIPIN_SIGN_WASM_PATTERNS = [
  { urlPattern: '*zhipin-sign*', requestStage: 'Request' },
  { urlPattern: '*.wasm', requestStage: 'Request' },
  { urlPattern: '*zpfe-captcha*', requestStage: 'Request' },
] as const;

/**
 * ⚠️ 注意：不能直接拦截 zhipin-sign 的所有请求！
 * 因为 __zp_stoken__ 依赖 zhipin-sign iframe 生成，拦截后所有请求 401。
 *
 * 正确策略：只拦截 zhipin-sign 中加载 .wasm 的请求（行为分析模块），
 * 保留 zhipin-sign 的 JS 主体（用于生成 stoken）。
 */
export const ZHIPIN_SIGN_WASM_ONLY_PATTERNS = [
  // 只拦截 WASM 文件（行为分析神经网络），不影响 stoken 生成
  { urlPattern: '*zhipin-sign*.wasm*', requestStage: 'Request' },
  { urlPattern: '*zpfe-captcha*.wasm*', requestStage: 'Request' },
  // aegis 行为上报（已有）— 确保覆盖 zhipin-sign 子域的上报
  { urlPattern: '*zhipin-sign*report*', requestStage: 'Request' },
  { urlPattern: '*zhipin-sign*collect*', requestStage: 'Request' },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// §5 安装行为层守卫（统一入口）
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 在页面上安装所有行为层增强。
 * 应在 installBossPageGuards 之后调用。
 */
export async function installBehaviorEnhancements(page: Page): Promise<void> {
  // 注入 performance.now hook（evaluateOnNewDocument 保证每次导航都生效）
  await page.evaluateOnNewDocument(PERFORMANCE_NOW_HOOK_SCRIPT);
  // 对当前已加载页面也立即注入
  await page.evaluate(PERFORMANCE_NOW_HOOK_SCRIPT).catch(() => {});
}

/**
 * 用于 Fetch.enable 时追加的 WASM 拦截规则。
 * 使用方式：在 boss_page_guards.ts 中 spread 进 patterns 数组。
 */
export { ZHIPIN_SIGN_WASM_ONLY_PATTERNS as BEHAVIOR_FETCH_PATTERNS };
